services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testPassword
      POSTGRES_DB: TestDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: TestApiFc
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=TestDB;Username=postgres;Password=testPassword
    ports:
      - "8080:80"
      - "5001:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
