// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Test.Persistence;

#nullable disable

namespace Test.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Test.Domain.Entities.MarcaAuto", b =>
                {
                    b.Property<int>("MarcaAutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MarcaAutoId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MarcaAutoId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("MarcaAutoId");

                    b.ToTable("MarcaAuto");

                    b.HasData(
                        new
                        {
                            MarcaAutoId = 1,
                            Codigo = "MAU01",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Descripcion = "Marca americana",
                            IsActive = true,
                            Nombre = "Ford"
                        },
                        new
                        {
                            MarcaAutoId = 2,
                            Codigo = "MAU02",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Descripcion = "Marca americana",
                            IsActive = true,
                            Nombre = "Chevrolet"
                        },
                        new
                        {
                            MarcaAutoId = 3,
                            Codigo = "MAU03",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Descripcion = "Marca americana",
                            IsActive = true,
                            Nombre = "Jeep"
                        },
                        new
                        {
                            MarcaAutoId = 4,
                            Codigo = "MAU04",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Descripcion = "Marca europea",
                            IsActive = true,
                            Nombre = "BMW"
                        },
                        new
                        {
                            MarcaAutoId = 5,
                            Codigo = "MAU05",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Descripcion = "Marca europea",
                            IsActive = true,
                            Nombre = "Mercedes-Benz"
                        },
                        new
                        {
                            MarcaAutoId = 6,
                            Codigo = "MAU06",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Descripcion = "Marca europea",
                            IsActive = true,
                            Nombre = "Volkswagen"
                        },
                        new
                        {
                            MarcaAutoId = 7,
                            Codigo = "MAU07",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Descripcion = "Marca asiática",
                            IsActive = true,
                            Nombre = "Toyota"
                        },
                        new
                        {
                            MarcaAutoId = 8,
                            Codigo = "MAU08",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Descripcion = "Marca asiática",
                            IsActive = true,
                            Nombre = "Honda"
                        },
                        new
                        {
                            MarcaAutoId = 9,
                            Codigo = "MAU09",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Descripcion = "Marca asiática",
                            IsActive = true,
                            Nombre = "Mitsubishi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
